# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http_tunnel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11http_tunnel.proto\x12\x05proto\x1a\x0butils.proto\"\xed\x01\n\x0bHttpRequest\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x30\n\x07headers\x18\x04 \x03(\x0b\x32\x1f.proto.HttpRequest.HeadersEntry\x12\x0c\n\x04\x62ody\x18\x05 \x01(\x0c\x12\x14\n\x0cisFinalChunk\x18\x06 \x01(\x08\x12\x12\n\nchunkIndex\x18\x07 \x01(\r\x12\x13\n\x0b\x63hunkOffset\x18\x08 \x01(\x04\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xe5\x01\n\x0cHttpResponse\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x12\n\nstatusCode\x18\x02 \x01(\r\x12\x31\n\x07headers\x18\x03 \x03(\x0b\x32 .proto.HttpResponse.HeadersEntry\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\x12\x14\n\x0cisFinalChunk\x18\x05 \x01(\x08\x12\x12\n\nchunkIndex\x18\x06 \x01(\r\x12\x13\n\x0b\x63hunkOffset\x18\x07 \x01(\x04\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\".\n\tHttpAbort\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\xfa\x01\n\rTunnelMessage\x12!\n\x07\x61uthReq\x18\x01 \x01(\x0b\x32\x0e.utils.AuthReqH\x00\x12!\n\x07\x61uthRsp\x18\x02 \x01(\x0b\x32\x0e.utils.AuthRspH\x00\x12%\n\x07request\x18\x03 \x01(\x0b\x32\x12.proto.HttpRequestH\x00\x12\'\n\x08response\x18\x04 \x01(\x0b\x32\x13.proto.HttpResponseH\x00\x12!\n\x05\x61\x62ort\x18\x05 \x01(\x0b\x32\x10.proto.HttpAbortH\x00\x12%\n\theartbeat\x18\x06 \x01(\x0b\x32\x10.utils.HeartbeatH\x00\x42\t\n\x07\x63ontent2K\n\nHttpTunnel\x12=\n\x0bStartTunnel\x12\x14.proto.TunnelMessage\x1a\x14.proto.TunnelMessage(\x01\x30\x01\x42\x1fZ\x1d\x63omfygw/pkg/proto/http_tunnelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'http_tunnel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035comfygw/pkg/proto/http_tunnel'
  _HTTPREQUEST_HEADERSENTRY._options = None
  _HTTPREQUEST_HEADERSENTRY._serialized_options = b'8\001'
  _HTTPRESPONSE_HEADERSENTRY._options = None
  _HTTPRESPONSE_HEADERSENTRY._serialized_options = b'8\001'
  _globals['_HTTPREQUEST']._serialized_start=42
  _globals['_HTTPREQUEST']._serialized_end=279
  _globals['_HTTPREQUEST_HEADERSENTRY']._serialized_start=233
  _globals['_HTTPREQUEST_HEADERSENTRY']._serialized_end=279
  _globals['_HTTPRESPONSE']._serialized_start=282
  _globals['_HTTPRESPONSE']._serialized_end=511
  _globals['_HTTPRESPONSE_HEADERSENTRY']._serialized_start=233
  _globals['_HTTPRESPONSE_HEADERSENTRY']._serialized_end=279
  _globals['_HTTPABORT']._serialized_start=513
  _globals['_HTTPABORT']._serialized_end=559
  _globals['_TUNNELMESSAGE']._serialized_start=562
  _globals['_TUNNELMESSAGE']._serialized_end=812
  _globals['_HTTPTUNNEL']._serialized_start=814
  _globals['_HTTPTUNNEL']._serialized_end=889
# @@protoc_insertion_point(module_scope)
