# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import http_tunnel_pb2 as http__tunnel__pb2


class HttpTunnelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTunnel = channel.stream_stream(
                '/proto.HttpTunnel/StartTunnel',
                request_serializer=http__tunnel__pb2.TunnelMessage.SerializeToString,
                response_deserializer=http__tunnel__pb2.TunnelMessage.FromString,
                )


class HttpTunnelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTunnel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HttpTunnelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTunnel': grpc.stream_stream_rpc_method_handler(
                    servicer.StartTunnel,
                    request_deserializer=http__tunnel__pb2.TunnelMessage.FromString,
                    response_serializer=http__tunnel__pb2.TunnelMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.HttpTunnel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HttpTunnel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTunnel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/proto.HttpTunnel/StartTunnel',
            http__tunnel__pb2.TunnelMessage.SerializeToString,
            http__tunnel__pb2.TunnelMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
