# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import taskq_pb2 as taskq__pb2


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginWork = channel.stream_stream(
                '/proto.TaskService/BeginWork',
                request_serializer=taskq__pb2.WorkerMessage.SerializeToString,
                response_deserializer=taskq__pb2.BrokerMessage.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/proto.TaskService/DownloadFile',
                request_serializer=taskq__pb2.DownloadRequest.SerializeToString,
                response_deserializer=taskq__pb2.DownloadResponse.FromString,
                )
        self.UploadFile = channel.stream_unary(
                '/proto.TaskService/UploadFile',
                request_serializer=taskq__pb2.UploadRequest.SerializeToString,
                response_deserializer=taskq__pb2.UploadResponse.FromString,
                )


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BeginWork(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginWork': grpc.stream_stream_rpc_method_handler(
                    servicer.BeginWork,
                    request_deserializer=taskq__pb2.WorkerMessage.FromString,
                    response_serializer=taskq__pb2.BrokerMessage.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=taskq__pb2.DownloadRequest.FromString,
                    response_serializer=taskq__pb2.DownloadResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=taskq__pb2.UploadRequest.FromString,
                    response_serializer=taskq__pb2.UploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BeginWork(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/proto.TaskService/BeginWork',
            taskq__pb2.WorkerMessage.SerializeToString,
            taskq__pb2.BrokerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.TaskService/DownloadFile',
            taskq__pb2.DownloadRequest.SerializeToString,
            taskq__pb2.DownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/proto.TaskService/UploadFile',
            taskq__pb2.UploadRequest.SerializeToString,
            taskq__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
