# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btaskq.proto\x12\x05proto\x1a\x0butils.proto\"\r\n\x0bWorkerReady\"0\n\x0cTaskProgress\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\t\"I\n\nTaskResult\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x1c\n\nTaskCancel\x12\x0e\n\x06taskId\x18\x01 \x01(\t\"\xf5\x01\n\rWorkerMessage\x12\x1e\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x0e.utils.AuthReqH\x00\x12#\n\x05ready\x18\x02 \x01(\x0b\x32\x12.proto.WorkerReadyH\x00\x12%\n\theartbeat\x18\x03 \x01(\x0b\x32\x10.utils.HeartbeatH\x00\x12\'\n\x08progress\x18\x04 \x01(\x0b\x32\x13.proto.TaskProgressH\x00\x12#\n\x06result\x18\x05 \x01(\x0b\x32\x11.proto.TaskResultH\x00\x12#\n\x06\x63\x61ncel\x18\x06 \x01(\x0b\x32\x11.proto.TaskCancelH\x00\x42\x05\n\x03msg\":\n\x08TaskInfo\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08taskName\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\"\x1c\n\nCancelTask\x12\x0e\n\x06taskId\x18\x01 \x01(\t\"\x87\x01\n\rBrokerMessage\x12!\n\x07\x61uthRsp\x18\x01 \x01(\x0b\x32\x0e.utils.AuthRspH\x00\x12#\n\x08taskInfo\x18\x02 \x01(\x0b\x32\x0f.proto.TaskInfoH\x00\x12\'\n\ncancelTask\x18\x03 \x01(\x0b\x32\x11.proto.CancelTaskH\x00\x42\x05\n\x03msg\"!\n\x0f\x44ownloadRequest\x12\x0e\n\x06\x66ileID\x18\x01 \x01(\t\"!\n\x10\x44ownloadResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"\x1e\n\rUploadRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\" \n\x0eUploadResponse\x12\x0e\n\x06\x66ileID\x18\x01 \x01(\t2\xca\x01\n\x0bTaskService\x12;\n\tBeginWork\x12\x14.proto.WorkerMessage\x1a\x14.proto.BrokerMessage(\x01\x30\x01\x12\x41\n\x0c\x44ownloadFile\x12\x16.proto.DownloadRequest\x1a\x17.proto.DownloadResponse0\x01\x12;\n\nUploadFile\x12\x14.proto.UploadRequest\x1a\x15.proto.UploadResponse(\x01\x42\x19Z\x17\x63omfygw/pkg/proto/taskqb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taskq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027comfygw/pkg/proto/taskq'
  _globals['_WORKERREADY']._serialized_start=35
  _globals['_WORKERREADY']._serialized_end=48
  _globals['_TASKPROGRESS']._serialized_start=50
  _globals['_TASKPROGRESS']._serialized_end=98
  _globals['_TASKRESULT']._serialized_start=100
  _globals['_TASKRESULT']._serialized_end=173
  _globals['_TASKCANCEL']._serialized_start=175
  _globals['_TASKCANCEL']._serialized_end=203
  _globals['_WORKERMESSAGE']._serialized_start=206
  _globals['_WORKERMESSAGE']._serialized_end=451
  _globals['_TASKINFO']._serialized_start=453
  _globals['_TASKINFO']._serialized_end=511
  _globals['_CANCELTASK']._serialized_start=513
  _globals['_CANCELTASK']._serialized_end=541
  _globals['_BROKERMESSAGE']._serialized_start=544
  _globals['_BROKERMESSAGE']._serialized_end=679
  _globals['_DOWNLOADREQUEST']._serialized_start=681
  _globals['_DOWNLOADREQUEST']._serialized_end=714
  _globals['_DOWNLOADRESPONSE']._serialized_start=716
  _globals['_DOWNLOADRESPONSE']._serialized_end=749
  _globals['_UPLOADREQUEST']._serialized_start=751
  _globals['_UPLOADREQUEST']._serialized_end=781
  _globals['_UPLOADRESPONSE']._serialized_start=783
  _globals['_UPLOADRESPONSE']._serialized_end=815
  _globals['_TASKSERVICE']._serialized_start=818
  _globals['_TASKSERVICE']._serialized_end=1020
# @@protoc_insertion_point(module_scope)
