# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0butils.proto\x12\x05utils\"\x0b\n\tHeartbeat\"u\n\x07\x41uthReq\x12\x11\n\tsessionId\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\t\x12\r\n\x05group\x18\x03 \x01(\t\x12\x10\n\x08hostName\x18\x04 \x01(\t\x12\x0c\n\x04info\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ptTasks\x18\x06 \x03(\t\"\'\n\x07\x41uthRsp\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\tB\x19Z\x17\x63omfygw/pkg/proto/utilsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027comfygw/pkg/proto/utils'
  _globals['_HEARTBEAT']._serialized_start=22
  _globals['_HEARTBEAT']._serialized_end=33
  _globals['_AUTHREQ']._serialized_start=35
  _globals['_AUTHREQ']._serialized_end=152
  _globals['_AUTHRSP']._serialized_start=154
  _globals['_AUTHRSP']._serialized_end=193
# @@protoc_insertion_point(module_scope)
